#!/usr/bin/env python

import sys, socket, select, time, json, random

# Your ID number
my_id = sys.argv[1]

# The ID numbers of all the other replicas
replica_ids = sys.argv[2:]

# Connect to the network. All messages to/from other replicas and clients will
# occur over this socket
sock = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
sock.connect(my_id)

NUM_REPLICAS = len(replica_ids) + 1
HEARTBEAT = 0.1
ELECTION_MIN = 150
ELECTION_MAX = 300

last = time.time()

state = 'follower'
leader = 'FFFF'
term = 0
votes = 0
election_timeout = random.randint(ELECTION_MIN, ELECTION_MAX) / 1000.

commitIndex = -1
entries = []

nextIndex = {}
matchIndex = {}
for replica in replica_ids:
    nextIndex[replica] = 0
    matchIndex[replica] = -1

log = []
kv_store = {}

while True:
    if state == 'follower':
        ready = select.select([sock], [], [], 0.1)[0] 
        if sock in ready:
            msg_raw = sock.recv(32768)
                
            if len(msg_raw) == 0: continue
            
            msg = json.loads(msg_raw)
            if msg['type'] in ['get', 'put']:
                res = {'src': my_id, 'dst': msg['src'], 'leader': leader, 'type': 'redirect', 'MID': msg['MID']}
                sock.send(json.dumps(res))

            if msg['type'] == 'RequestVote' and msg['term'] > term:
                last = time.time()
                term = msg['term']
                leader = msg['src']
                # print(my_id + ' voted for ' + leader)
                res = {'src': my_id, 'dst': leader, 'leader': leader, 'type': 'vote', 'term': term}
                sock.send(json.dumps(res))

            if msg['type'] == 'AppendEntries':
                last = time.time()
                if len(msg['entries']) == 0:
                    term = msg['term']
                    leader = msg['src']
                elif msg['term'] < term or (msg['prevLogIndex'] >= 0 and len(log) > msg['prevLogIndex'] and log[msg['prevLogIndex']]['term'] != msg['prevLogTerm']):
                    res = {'src': my_id, 'dst': leader, 'leader': leader, 'type': 'AppendEntriesRes', 'success': False}
                    sock.send(json.dumps(res))
                else:
                    log = log[:msg['prevLogIndex']+1]
                    log.extend(msg['entries'])
                    if msg['leaderCommit'] > commitIndex:
                        for i in range(commitIndex + 1, msg['leaderCommit'] + 1):
                            cmd = log[i]['command']
                            kv_store[cmd['key']] = cmd['value']
                            res = {'src': my_id, 'dst': leader, 'leader': leader, 'type': 'ok', 'MID': cmd['MID']}
                            sock.send(json.dumps(res))
                        commitIndex = msg['leaderCommit']
                    res = {'src': my_id, 'dst': leader, 'leader': leader, 'type': 'AppendEntriesRes', 'success': True, 'matchIndex': len(log)-1}
                    sock.send(json.dumps(res))


        elif time.time() - last > election_timeout:
            term += 1
            votes = 1
            state = 'candidate'
            last = time.time()
            # print(my_id + ' is a candidate')
            res = {'src': my_id, 'dst': 'FFFF', 'leader': 'FFFF', 'type': 'RequestVote', 'term': term}
            sock.send(json.dumps(res))

    if state == 'candidate':
        ready = select.select([sock], [], [], 0.1)[0] 
        if sock in ready:
            msg_raw = sock.recv(32768)
                
            if len(msg_raw) == 0: continue
            
            msg = json.loads(msg_raw)
            
            if msg['type'] in ['get', 'put']:
                res = {'src': my_id, 'dst': msg['src'], 'leader': leader, 'type': 'fail', 'MID': msg['MID']}
                sock.send(json.dumps(res))

            if msg['type'] == 'vote':
                votes += 1
                if votes > NUM_REPLICAS / 2:
                    state = 'leader'
                    leader = my_id
                    # print('Elected ' + my_id)
                    res = {'src': my_id, 'dst': 'FFFF', 'leader': leader, 'type': 'AppendEntries', 'term': term, 'entries': []}
                    sock.send(json.dumps(res))

            if msg['type'] == 'AppendEntries' and msg['term'] >= term:
                last = time.time()
                state = 'follower'
                leader = msg['src']

        elif time.time() - last > election_timeout:
            term += 1
            votes = 1
            state = 'candidate'
            election_timeout = random.randint(ELECTION_MIN, ELECTION_MAX) / 1000.
            last = time.time()
            # print(my_id + ' is a candidate again')
            res = {'src': my_id, 'dst': 'FFFF', 'leader': 'FFFF', 'type': 'RequestVote', 'term': term}
            sock.send(json.dumps(res))

    if state == 'leader':
        ready = select.select([sock], [], [], 0.1)[0] 
        if sock in ready:
            msg_raw = sock.recv(32768)
                
            if len(msg_raw) == 0: continue
            
            msg = json.loads(msg_raw)    
            
            if msg['type'] == 'RequestVote' and msg['term'] > term:
                last = time.time()
                state = 'follower'
                term = msg['term']
                leader = msg['src']
                # print(my_id + ' voted for ' + leader)
                res = {'src': my_id, 'dst': leader, 'leader': leader, 'type': 'vote', 'term': term}
                sock.send(json.dumps(res))

            if msg['type'] == 'AppendEntriesRes':
                replica = msg['src']
                if msg['success']:
                    matchIndex[replica] = msg['matchIndex']
                    nextIndex[replica] = matchIndex[replica] + 1
                    majority = sorted(matchIndex.values(), reverse=True)[NUM_REPLICAS/2]
                    if majority > commitIndex and log[majority]['term'] == term:
                        for i in range(commitIndex + 1, majority + 1):
                            cmd = log[i]['command']
                            kv_store[cmd['key']] = cmd['value']
                            res = {'src': my_id, 'dst': cmd['src'], 'leader': leader, 'type': 'ok', 'MID': cmd['MID']}
                            sock.send(json.dumps(res))
                        commitIndex = majority
                else:
                    nextIndex[replica] -= 1
                    res = {'src': my_id, 'dst': replica, 'leader': leader, 'type': 'AppendEntries', 'term': term, 'leaderCommit': commitIndex}
                    res['entries'] = log[nextIndex[replica]:]
                    res['prevLogIndex'] = nextIndex[replica]-1
                    res['prevLogTerm'] = -1 if res['prevLogIndex'] == -1 else log[res['prevLogIndex']]['term']
                    sock.send(json.dumps(res))

            if msg['type'] == 'get':
                key = msg['key']
                value = kv_store[key] if key in kv_store else ''
                res = {'src': my_id, 'dst': msg['src'], 'leader': leader, 'type': 'ok', 'MID': msg['MID'], 'value': value}
                sock.send(json.dumps(res))

            if msg['type'] == 'put':
                log.append({'command': {'key': msg['key'], 'value': msg['value'], 'src': msg['src'], 'MID': msg['MID']}, 'term': term})

        if time.time() - last > HEARTBEAT:
            for replica in replica_ids:
                res = {'src': my_id, 'dst': replica, 'leader': leader, 'type': 'AppendEntries', 'term': term, 'leaderCommit': commitIndex}
                res['entries'] = log[nextIndex[replica]:]
                res['prevLogIndex'] = nextIndex[replica]-1
                res['prevLogTerm'] = -1 if res['prevLogIndex'] == -1 else log[res['prevLogIndex']]['term']
                sock.send(json.dumps(res))
            last = time.time()

